### ISSUE TITLE
deprecated methods on webpack

### ISSUE THREAD

**Issue by joonas-yoon** [joonas-yoon/speech-translator-server#5]
When `docker-compose up`, it gets error message as following:

```
$ docker-compose up
WARNING: Some services (app) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
Building app
Step 1/8 : FROM node:10.13.0-slim
 ---> c0e8e932527c
Step 2/8 : COPY . /src
 ---> Using cache
 ---> 1378ebbf8659
Step 3/8 : RUN  cd /src/backend; npm install
 ---> Using cache
 ---> bd12b78298a8
Step 4/8 : RUN  cd /src/frontend; npm install
 ---> Using cache
 ---> 5a64896e6d19
Step 5/8 : EXPOSE 3000
 ---> Using cache
 ---> 1d0b6cd385d9
Step 6/8 : WORKDIR /src
 ---> Using cache
 ---> cf524cdc3b21
Step 7/8 : RUN npm run build
 ---> Running in 4350b4a3ba9c

> speech-translator-app@0.1.2 build /src
> cd frontend && npm run build


> speech-translator@1.0.0 build /src/frontend
> node build/build.js

/src/frontend/node_modules/webpack/lib/webpack.js:189
                        throw new RemovedPluginError(errorMessage);
                        ^

Error: webpack.optimize.CommonsChunkPlugin has been removed, please use config.optimization.splitChunks instead.
    at Object.get [as CommonsChunkPlugin] (/src/frontend/node_modules/webpack/lib/webpack.js:189:10)
    at Object.<anonymous> (/src/frontend/build/webpack.prod.conf.js:86:26)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/src/frontend/build/build.js:12:23)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! speech-translator@1.0.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the speech-translator@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-14T18_06_59_269Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! speech-translator-app@0.1.2 build: `cd frontend && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the speech-translator-app@0.1.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-14T18_06_59_285Z-debug.log
ERROR: Service 'app' failed to build: The command '/bin/sh -c npm run build' returned a non-zero code: 1
```

**Comment by joonas-yoon** [comment]
It's message for webpack v4, but frontend uses webpack 3.6.0 in current master branch.

This is not an issue yet.
