### ISSUE TITLE
Cannot find module 'chalk'

### ISSUE THREAD

**Issue by joonas-yoon** [joonas-yoon/speech-translator-server#6]
## Descriptive title

- [x] frontend (node.js, docker, ...)
- [ ] backend (vue.js, webpack, ...)

Cannot find module 'chalk' when `npm run build` for frontend.

## Environments

* **Environment name and version** : npm 6.14.4
* **Operating System and version** : Windows 10 64bit (Build 18362)
* Link to your project :

### Context

On `~/app/frontend` I tried to build Vue.js
```
$ npm run build
```

## Actual Behavior

```
$ npm run build

> speech-translator@1.0.0 build C:\Users\joona\speech-translator-server\app\frontend
> node build/build.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\joona\speech-translator-server\app\frontend\build\check-versions.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! speech-translator@1.0.0 build: `node build/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the speech-translator@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\joona\AppData\Roaming\npm-cache\_logs\2020-08-14T19_04_45_928Z-debug.log
```

**Comment by joonas-yoon** [comment]
https://github.com/vuejs-templates/pwa/issues/152

`npm install` is skipping devDependencies when has `NODE_ENV` as `production`.

It can be resolved with:
```
$ npm --production=false install
```
